export * from "./auth";
export * from "./branches";
export * from "./groups";
export * from "./course";
export * from "./payments";
export * from "./incomes";
export * from "./outcomes";
export * from "./rooms";
export * from "./auth";
export * from "./student";
export * from "./teacher";
export * from "./pupils";
export * from "./employees";
export * from "./statistics";
export * from "./lesson";
export * from "./classifiers";
export * from "./extraPhoneNumbers";
export * from './clients'
export * from './photos'
export * from './posts'
export * from './schedule'
export * from './materials'
export * from './globalSearch'
