export * from './auth';
export * from './branches';
export * from './classifiers';
export * from './clients';
export * from './courses';
export * from './employees';
export * from './extra-phone-number';
export * from './groups';
export * from './incomes';
export * from './lessons';
export * from './materials';
export * from './outcomes';
export * from './payments';
export * from './photos';
export * from './posts';
export * from './pupils';
export * from './rooms';
export * from './teachers';
export * from './users';
export * from './statistics';
export * from './clients'
export * from './schedule'
export * from './globalSearch'